
# For more information on how to configure this file, please see:
# https://github.com/fishtown-analytics/dbt/blob/master/sample.profiles.yml
config:
    send_anonymous_usage_stats: False
    use_colors: True
    printer_width: 180

default:
  target: integration

  outputs:
    integration:
      type: bigquery
      method: service-account
      project: at-dry-run-integration
      schema: dry_run
      location: EU
      threads: 8
      timeout_seconds: 300
      keyfile: /etc/bq_svc.json